### ISSUE TITLE
Add to flintmc.net

### ISSUE THREAD

**Issue by strich3** [Fesaa/Cubepanion#2]

**Comment by Fesaa** [comment]
Heya!

I have to rework a bunch of stuff with the 1.19 release since stuff changed. I'm quite busy dealing with bug reports as well, so this might be a while. 

Feel free to contribute, to help out

**Comment by strich3** [comment]
I can try it! :D

**Comment by strich3** [comment]
I can also add the german translations later

**Comment by Fesaa** [comment]
I'm going to get this done in the next few days :)
